-- Root for the mechanically extracted model. The contents of Extracted/ are
-- generated by `make extract` (charon + aeneas) and committed on purpose:
-- reviewing this diff is how you notice that a Rust change altered the model's
-- meaning. Do not hand-edit.
import Extracted.LeanersRender
